### ISSUE TITLE
APA data preprocessing

### ISSUE THREAD

**Issue by kmpujar** [kmpujar/Machine-Transliteration#1]
Cheng, please get the data from APA data set and process it to form the training data.

**Comment by CEMREYIM** [comment]
ARPABET: https://en.wikipedia.org/wiki/ARPABET

Dataset: http://www.speech.cs.cmu.edu/cgi-bin/cmudict

Potentially: http://websites.psychology.uwa.edu.au/school/MRCDatabase/uwa_mrc.htm
